apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
              hostPort: 80
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx-svc
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: nginx
  name: nginx
  annotations:
    cert-manager.io/cluster-issuer: trust-anchor
spec:
  ingressClassName: nginx
  rules:
    - host: nginx.kind.cluster
      http:
        paths:
          - backend:
              service:
                name: nginx-svc
                port:
                  number: 80
            pathType: ImplementationSpecific
  tls:
    - secretName: nginx-tls-certificate
      hosts:
        - nginx.kind.cluster
