# .github/workflows/create-branch.yml
name: Create Branch, Commit Changes, and PR via Script (with PAT)

# Controls when the workflow will run
on:
  workflow_dispatch: # Allows manual triggering
    inputs:
      new_branch_name:
        description: "Name for the new branch (e.g., feature/my-new-feature)"
        required: true
        default: "feature/new-branch"
      base_branch_name:
        description: "Branch to base the new branch on AND target for the PR"
        required: true
        default: "main" # Or your default branch
      commit_message:
        description: "Commit message for the automated change"
        required: false
        default: "feat: Add placeholder file"
      # pr_title:
      #   description: "Title for the Pull Request"
      #   required: false # Optional, provide a default
      #   default: "New Feature Branch"
      # pr_body:
      #   description: "Body/description for the Pull Request"
      #   required: false # Optional
      #   default: "Pull request automatically created by workflow."
      my_pat:
        description: "GitHub Personal Access Token (PAT) with repo scope"
        required: true
        default: "" # Leave empty, will be set in the workflow

jobs:
  create_branch_commit_pr_job:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Create new branch
        id: create_branch
        uses: actions/github-script@v7
        with:
          github-token: ${{ inputs.my_pat }}
          script: |
            // Get inputs from the workflow_dispatch event
            const newBranch = '${{ github.event.inputs.new_branch_name }}';
            const baseBranch = '${{ github.event.inputs.base_branch_name }}';
            const repoUrl = context.payload.repository.html_url;
            const ref = `refs/heads/${newBranch}`;

            console.log(`Attempting to create branch '${newBranch}' from '${baseBranch}' using PAT authentication...`);
            try {
              console.log(`Fetching SHA for base branch '${baseBranch}'...`);
              const { data: baseBranchRef } = await github.rest.git.getRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `heads/${baseBranch}`,
              });
              const baseSha = baseBranchRef.object.sha;
              console.log(`Base SHA for '${baseBranch}' is '${baseSha}'.`);

              console.log(`Creating ref '${ref}' pointing to SHA '${baseSha}'...`);
              await github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: ref,
                sha: baseSha,
              });
              const branchUrl = `${repoUrl}/tree/${newBranch}`;
              const successMsg = `Successfully created branch: [${newBranch}](${branchUrl})`;
              console.log(successMsg);

              core.summary.addHeading('Branch Creation', 2);
              core.summary.addRaw(`* ${successMsg}\n`, true);
              core.summary.addRaw(`* Base Branch: \`${baseBranch}\`\n`);
              core.summary.addSeparator();
              await core.summary.write({ overwrite: false });

              core.setOutput("new_branch_name_output", newBranch);
            } catch (error) {
              console.error(`Error creating branch: ${error.message}`);
              const errorMsg = `Failed to create branch '${newBranch}'.`;

              core.summary.addHeading('Branch Creation', 3);
              core.summary.addRaw(`❌ ${errorMsg} Error: ${error.message}`);
              core.summary.addSeparator();
              await core.summary.write({ overwrite: false });

              if (error.status === 422) {
                core.setFailed(`Failed to create branch '${newBranch}'. It might already exist. Error: ${error}`);
              } else {
                core.setFailed(`Failed to create branch '${newBranch}'. Error: ${error}`);
              }
            }

      - name: Checkout new branch
        if: success() && steps.create_branch.outputs.new_branch_name_output
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.create_branch.outputs.new_branch_name_output }}
          fetch-depth: 1

      - name: Create commit
        if: success()
        run: |
          echo "Adding a new line generated by workflow at $(date)" >> README.md
          # Or create a new file:
          # echo "This file was created by the workflow" > generated-file-${{ github.run_id }}.txt

          # Configure Git
          # Use the GitHub Actions bot user as the committer
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Commit the changes
          git add . # Add all changes

          if git diff --staged --quiet; then
            echo "No changes to commit."
            echo "commit_sha=NONE" >> $GITHUB_OUTPUT # Set output even if no commit
          else
            git commit -m "${{ github.event.inputs.commit_message }}" # Use input for commit message
            git push origin ${{ steps.create_branch.outputs.new_branch_name_output }}
            COMMIT_SHA=$(git rev-parse HEAD) # Get the SHA of the new commit
            echo "Changes committed and pushed to ${{ steps.create_branch.outputs.new_branch_name_output }}. Commit SHA: $COMMIT_SHA"
            echo "commit_sha=$COMMIT_SHA" >> $GITHUB_OUTPUT # Output the commit SHA
          fi

      - name: Update Summary with Commit Info
        if: always() && steps.create_branch.outcome != 'failure'
        uses: actions/github-script@v7
        with:
          script: |
            const commitSha = '${{ steps.create_commit.outputs.commit_sha }}';
            if (!commitSha) {
               console.log('Commit step did not produce output (likely skipped or failed early).');
               return;
            }

            const branchName = '${{ steps.create_branch.outputs.new_branch_name_output }}';
            const repoUrl = context.payload.repository.html_url;

            core.summary.addHeading('Commit Details', 3);

            if (commitSha && commitSha !== 'NONE') {
              const commitUrl = `${repoUrl}/commit/${commitSha}`;
              core.summary.addRaw(`✅ Commit `)
                        .addLink(commitSha.substring(0,7), commitUrl)
                        .addRaw(` pushed to branch \`${branchName}\`.\n`);
            } else if (commitSha === 'NONE') {
              core.summary.addRaw(`ℹ️ No file changes detected; no commit was created on branch \`${branchName}\`.\n`);
            } else {
              // This case implies the commit step failed before producing output - handled by the initial check
               core.summary.addRaw(`* ❌ Failed to get commit details for branch \`${branchName}\` (Step likely failed).\n`);
            }
            core.summary.addSeparator();
            await core.summary.write({ overwrite: false });

      - name: Create Pull Request
        if: success()
        uses: actions/github-script@v7
        with:
          github-token: ${{ inputs.my_pat }}
          script: |
            const newBranch = '${{ steps.create_branch.outputs.new_branch_name_output }}';
            const baseBranch = '${{ github.event.inputs.base_branch_name }}';
            const runNumber = process.env.GITHUB_RUN_NUMBER;
            const githubUrl = process.env.GITHUB_SERVER_URL;
            const prTitle = `Version Picker changes: Run#${runNumber}`;
            const prBody = `
              Version Picker changes:
              GITHUB_RUN_NUMBER: [${runNumber} - Overview](${githubUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId})
              GITHUB_RUN_ID: ${context.runId}
              Date: ${new Date().toISOString().replace('T', ' ').slice(0, 19)}
            `.trim();

            console.log(`Creating Pull Request for branch '${newBranch}' targeting '${baseBranch}'...`);

            try {
              const { data: pullRequest } = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: prTitle,
              head: newBranch,
              base: baseBranch,
              body: prBody,
              draft: false,
              });

              prUrl = pullRequest.html_url;
              prNumber = pullRequest.number;
              const successMsg = `Successfully created Pull Request [#${prNumber}](${prUrl})`;
              console.log(successMsg);
              core.setOutput("pr_url", prUrl);
              core.setOutput("pr_number", prNumber);

              core.summary.addHeading('Pull Request Creation', 3);
              core.summary.addRaw(`* Successfully created Pull Request `)
                        .addLink(`#${prNumber}`, prUrl)
                        .addRaw(`\n`);
              core.summary.addRaw(`* Target Branch: \`${baseBranch}\``);
              core.summary.addSeparator();
              await core.summary.write({ overwrite: false });

            } catch (error) {
              console.error(`Failed to create Pull Request: ${error.message}`);
              const errorMsg = `Failed to create Pull Request for branch '${newBranch}' targeting '${baseBranch}'.`;

              core.summary.addHeading('Pull Request Creation', 3);
              core.summary.addRaw(`❌ ${errorMsg} Error: ${error.message}\n`);
              if (error.message.includes("A pull request already exists")) {
                 summaryContent += `ℹ️ An active pull request likely already exists for this branch.\n`;
              }
              core.summary.addSeparator();
              await core.summary.write({ overwrite: false });

              if (error.message.includes("A pull request already exists")) {
              core.warning(`PR already exists for branch '${newBranch}'.`);
              } else if (error.message.includes("No commits between")) {
              core.warning(`No commits between '${newBranch}' and '${baseBranch}'.`);
              } else {
              core.setFailed(`Error creating Pull Request: ${error.message}`);
              }
            }
