name: End to End Tests

on:
  workflow_dispatch:
    inputs:
      arc_name:
        description: "Target ARC name used for `runs-on` in job"
        required: true
        default: self-hosted

jobs:
  e2e-test:
    runs-on: ${{ inputs.arc_name }}
    strategy:
      matrix:
        k8s-version: ["v1.30.0"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.30.0

      # https://github.com/helm/kind-action
      - name: Install k8s ${{ matrix.k8s-version }}
        uses: helm/kind-action@v1.10.0
        with:
#          version: v0.19.0
          cluster_name: kind
          config: ./k8s/kind-config.yaml
          kubectl_version: v1.30.0
          node_image: kindest/node:${{ matrix.k8s-version }}

      - name: Testing
        run: |
          # kind get kubeconfig --name kind
          kubectl wait --for=condition=Ready nodes --all --timeout=5m
          kubectl get nodes -o wide

      # - name: Install Nginx ingress
      #   run: ./scripts/kind-add-ingress-nginx.sh

      # - name: Install MetalLB
      #   run: ./scripts/kind-add-metallb.sh

      - name: Create infra on kind
        run: |
          make prepare-cluster

#      - name: Install Externa DNS
#        run: ./scripts/kind-add-external-dns.sh

#      - name: Deploy nginx
#        run: |
#          kubectl apply -f ./k8s/deployment/nginx.yaml
#          kubectl rollout status deployment/nginx -n default
#          kubectl get pods -n default
#
#      - name: Sleep for 2 minutes
#        run: sleep 120s
#        shell: bash
#
#      - name: Test app
#        run: |
#          curl https://nginx.kind.cluster

